"""Add library models clean

Revision ID: b3bbe47c5eac
Revises: 20260110_02
Create Date: 2026-01-16 21:45:26.628461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3bbe47c5eac'
down_revision: Union[str, Sequence[str], None] = '20260110_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storage_relpath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumb_relpath', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_sha256'), ['sha256'], unique=False)

    op.create_table('auditevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('cover_face_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('faces_count', sa.Integer(), nullable=False),
    sa.Column('assets_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personref',
    sa.Column('person_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('face_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('person_id', 'bucket')
    )
    op.create_table('faceinstance',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bbox_x', sa.Integer(), nullable=False),
    sa.Column('bbox_y', sa.Integer(), nullable=False),
    sa.Column('bbox_w', sa.Integer(), nullable=False),
    sa.Column('bbox_h', sa.Integer(), nullable=False),
    sa.Column('face_crop_relpath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embed_dim', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('yaw', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('roll', sa.Float(), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faceinstance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faceinstance_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faceinstance_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_faceinstance_quality_score'), ['quality_score'], unique=False)

    # op.drop_table('items_fts_docsize')
    # op.drop_table('items_fts_idx')
    # op.drop_table('items_fts')
    # op.drop_table('items_fts_config')
    # op.drop_table('items_fts_data')
    # op.drop_table('items_fts_content')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_created_at'))
        batch_op.drop_index(batch_op.f('ix_categories_is_active'))
        batch_op.drop_index(batch_op.f('ix_categories_sort_order'))

    with op.batch_alter_table('category_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_embeddings_dim'))
        batch_op.drop_index(batch_op.f('ix_category_embeddings_updated_at'))

    with op.batch_alter_table('item_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_embeddings_created_at'))
        batch_op.drop_index(batch_op.f('ix_item_embeddings_dim'))

    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_tags_created_at'))

    with op.batch_alter_table('item_versions', schema=None) as batch_op:
        batch_op.alter_column('prompt_blob',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_item_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_item_versions_item_created'))
        batch_op.drop_index(batch_op.f('ix_item_versions_v'))
        batch_op.drop_constraint(batch_op.f('uq_item_versions_item_v'), type_='unique')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('series_name_snapshot',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('media_path',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('thumb_path',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('poster_path',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('auto_candidates_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_items_category'))
        batch_op.drop_index(batch_op.f('ix_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_items_created_at_id'))
        batch_op.drop_index(batch_op.f('ix_items_current_version_id'))
        batch_op.drop_index(batch_op.f('ix_items_media_type'))
        batch_op.drop_index(batch_op.f('ix_items_series'))
        batch_op.drop_index(batch_op.f('ix_items_series_id'))
        batch_op.drop_index(batch_op.f('ix_items_title'))
        batch_op.drop_index(batch_op.f('ix_items_tool_id'))
        batch_op.drop_index(batch_op.f('ix_items_tool_media'))
        batch_op.drop_index(batch_op.f('ix_items_updated_at'))
        batch_op.create_index(batch_op.f('ix_items_auto_confidence'), ['auto_confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_is_category_locked'), ['is_category_locked'], unique=False)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_created_at'))
        batch_op.drop_index(batch_op.f('ix_series_current_version_id'))
        batch_op.drop_index(batch_op.f('ix_series_updated_at'))

    with op.batch_alter_table('series_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_tags_created_at'))

    with op.batch_alter_table('series_versions', schema=None) as batch_op:
        batch_op.alter_column('base_prompt_blob',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_series_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_series_versions_v'))
        batch_op.drop_constraint(batch_op.f('uq_series_versions_series_v'), type_='unique')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_created_at'))

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_created_at'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('series_versions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_series_versions_series_v'), ['series_id', 'v'])
        batch_op.create_index(batch_op.f('ix_series_versions_v'), ['v'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_versions_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('note',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('base_prompt_blob',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('series_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_tags_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_current_version_id'), ['current_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_is_category_locked'))
        batch_op.drop_index(batch_op.f('ix_items_auto_confidence'))
        batch_op.create_index(batch_op.f('ix_items_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_tool_media'), ['tool_id', 'media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_tool_id'), ['tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_series'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_current_version_id'), ['current_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_created_at_id'), ['created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_category'), ['category_id'], unique=False)
        batch_op.alter_column('auto_candidates_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('poster_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('thumb_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('media_path',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('series_name_snapshot',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('item_versions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_item_versions_item_v'), ['item_id', 'v'])
        batch_op.create_index(batch_op.f('ix_item_versions_v'), ['v'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_versions_item_created'), ['item_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_versions_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('note',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('prompt_blob',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_tags_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('item_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_embeddings_dim'), ['dim'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_embeddings_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('category_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_embeddings_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_embeddings_dim'), ['dim'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_created_at'), ['created_at'], unique=False)

    op.create_table('items_fts_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.Column('c3', sa.NullType(), nullable=True),
    sa.Column('c4', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('items_fts',
    sa.Column('item_id', sa.NullType(), nullable=True),
    sa.Column('title', sa.NullType(), nullable=True),
    sa.Column('series', sa.NullType(), nullable=True),
    sa.Column('prompt', sa.NullType(), nullable=True),
    sa.Column('tags', sa.NullType(), nullable=True)
    )
    op.create_table('items_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('items_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faceinstance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faceinstance_quality_score'))
        batch_op.drop_index(batch_op.f('ix_faceinstance_bucket'))
        batch_op.drop_index(batch_op.f('ix_faceinstance_asset_id'))

    op.drop_table('faceinstance')
    op.drop_table('personref')
    op.drop_table('person')
    op.drop_table('auditevent')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_sha256'))
        batch_op.drop_index(batch_op.f('ix_asset_kind'))
        batch_op.drop_index(batch_op.f('ix_asset_created_at'))

    op.drop_table('asset')
    # ### end Alembic commands ###
